name: 'Setup Lazarus environment'

description: 'Setup a Lazarus environment adding it to the PATH'

branding:
  icon: 'chevrons-right'
  color: 'blue'

inputs:
  lazarus-version:
    description: 'Version of Lazarus'
    required: true
    default: 'dist'
  include-packages:
    description: 'Include packages that the project needs'
    required: false
  with-cache:
    description: 'Use cache for installer files'
    required: false
    default: "false"
  os-arch:
    description: 'Installing 32-bit Lazarus on Windows 64'
    required: false
    default: 'x64'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
